name: AVD Azure Image Builder

on:
  push:
    branches:
      - "main"
    paths:
      - 'imageBuilder'
      - 'carml/0.10.0/modules/Microsoft.VirtualMachineImages'
  workflow_dispatch:

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  Location: "norwayeast"
  AVDSubId: "a7693725-2adf-4eff-98eb-fc941246426d"
  ImageBuilderRGName: "rg-image-builder"
  runNumber: ${{ github.run_number }}

jobs:
  azure-image-builder:
    if: github.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  
      # Authenticate to Az CLI using OIDC
    - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
      # Deploy
    - name: "Build Azure Image Builder Template"
      uses: Azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ env.AVDSubId }}
        region: ${{ env.Location }}
        template: imageBuilder\deploy.bicep
        deploymentName: create_zone-0-${{ env.runNumber }}
        failOnStdErr: false
