name: AVD Azure Image Builder

on:
  push:
    branches:
      - "main"
    paths:
      - 'imageBuilder'
      - 'carml/0.10.0/modules/Microsoft.VirtualMachineImages'
  workflow_dispatch:

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  Location: "norwayeast"
  AVDSubId: "a7693725-2adf-4eff-98eb-fc941246426d"
  ServiceObjectRGName: "alz-centrallogging"
  HubNetworkSubId: "0f18a4f9-2e78-43d0-b06a-6a490469a7a6"
  runNumber: ${{ github.run_number }}

jobs:
  azure-image-builder:
    if: github.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest
    steps:
      # Compostite Action to verify the Bicep file
    - name: Bicep WhatIf
      uses: ./.github/actions/bicep-whatif.yml
      # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2    
      # Authenticate to Az CLI using OIDC
    - name: Login via OIDC
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      # Deploy
    - name: "Bicep Deployment"
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az deployment sub create \
            --name deploy-${{ github.run_id }} \
            --template-file imageBuilder\deploy.bicep \
            --location $Location 